version: "3.9"

services:
  mongo:
    image: mongo:7.0
    container_name: key-generation-servce-mongo1
    command: ["mongod"]
    ports:
      - "27017:27017"
    volumes:
      - mongo1_data:/data/db
  redis:
    image: redis:7.2
    container_name: key-generation-service-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo1_data:
  redis_data:
