spring:
  application:
    name: key-generation-service
  autoconfigure:
    exclude: org.springframework.boot.data.mongodb.autoconfigure.DataMongoAutoConfiguration
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017,localhost:27018/key_generation_service
        ?replicaSet=rs0
        &authSource=admin
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    url: mongodb://admin:admin@localhost:27017,localhost:27018/shortener
      ?replicaSet=rs0
      &authSource=admin